spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/victoradepoju/config-server
          default-label: main
          timeout: 20
          clone-on-start: true
          force-pull: true

server:
  port: 8200